DROP TABLE IF EXISTS BANK_CONSENT_PERM;

DROP TABLE IF EXISTS BANK_CONSENT_DATA;

CREATE TABLE BANK_CONSENT_DATA (
   Id INT AUTO_INCREMENT PRIMARY KEY,
   ConsentId VARCHAR(50) NOT NULL UNIQUE,
   StatusVal VARCHAR(20) NOT NULL,
   StatusUpdateDateTime TIMESTAMP,
   CreationDateTime TIMESTAMP,
   ExpirationDateTime TIMESTAMP,
   TransactionFromDateTime TIMESTAMP,
   TransactionToDateTime TIMESTAMP
);


CREATE TABLE BANK_CONSENT_PERM (
 PId INT AUTO_INCREMENT PRIMARY KEY,
 PName VARCHAR(25),
 Id INT NOT NULL,
 KEY `Id` (`Id`),
CONSTRAINT `F_Id` FOREIGN KEY (`Id`) REFERENCES BANK_CONSENT_DATA(`Id`)
);

commit;

SHOW TABLES;

SELECT * FROM BANK_CONSENT_PERM;